[build]
builder = "Nixpacks"
language = "node"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.build]
cmds = ["npm install", "npm run build"]

[phases.start]
cmd = "npx serve dist -l $PORT"